server:
  port: 8001
spring:
  application:
    name: ccwsystem-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/schoolsystem?characterEncoding=utf8&useSSL=false #数据库url设置
    username: root
    password: 4795
    dbcp2:
      min-idle: 2 #数据库连接池最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 10 #最大连接数
      max-wait-millis: 1000 #等待超时时间
  redis:
    database: 0 # 选择的数据库
    host: 127.0.0.1 # 地址
    port: 6379 # 端口
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-wait: -1ms  # 最大等待时间
        max-idle: 8
        min-idle: 0
    timeout: 1000ms # 超时时间
  data:
    elasticsearch:
      cluster-name: school_system
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
