server:
  port: 4795
spring:
  application:
    name: jsuccw-zuul-gateway
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource #当前数据库操作类型
      driver-class-name: com.mysql.jdbc.Driver  # MySQL驱动包
      url: jdbc:mysql://172.17.0.1:3306/schoolsystem?characterEncoding=utf8&useSSL=false #数据库url设置
      username: root
      password: 4795
      dbcp2:
        min-idle: 2 #数据库连接池最小维持连接数
        initial-size: 5 #初始化连接数
        max-total: 10 #最大连接数
        max-wait-millis: 1000 #等待超时时间
  redis:
      database: 0
      host: 172.17.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      timeout: 1000ms
  mail:
      host: smtp.mxhichina.com
      username: admin@jsuacm.cn
      password: Ccw2110.
      default-encoding: UTF-8
  thymeleaf:
      cache: true
      servlet:
        content-type: text/html
      encoding: UTF-8
      mode: HTML
      suffix: .html

eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.1:7001/eureka

  instance:
    instance-id: gateway-4795.com
    prefer-ip-address: true

zuul:
  ignored-services: "*"
  routes:
    myuser1.path: /ccw/**
    myuser1.serviceId: ccwsystem-8001
  host:
      connect-timeout-millis: 60000
      socket-timeout-millis: 60000
